### ISSUE TITLE
Unable to get ObjectId of inserted object using insertOneObs

### ISSUE THREAD

**Issue by 839998664** [EnricoPicci/observable-mongo#2]
Unable to get the ObjectId of the object inserted using insertOneObs. The insertOneObs returns the insertedId as _.values(insertedId). Not sure why the lodash function values is used to convert the object key to array in the insertOneObs. It may be valid for insertMany though.

**Comment by EnricoPicci** [comment]
You are right. It makes more sense to return the ObjecID from the execution of insertOneObs.
I have created a new version, 2.3.10, which should address your point.
For the time being I close the issue. Let me know if it does not work.
